sources = Split("""aiff.cpp
	double_dispatch_factory.cpp
	filefact.cpp
	ieee754.cpp
	memory_producer.cpp
	memory_writer.cpp
	objfact.cpp
	progress.cpp
	raw_file.cpp
	stdafx.cpp
	wav.cpp
	""")

Import("env")
napl = env.Library( 'napl', sources)
env.Export("napl")
